###
POST http://localhost:8101/create
Content-Type: application/json

{
  "amount": 30
}

###
GET localhost:8101/accounts

###
POST http://localhost:8102/create
Content-Type: application/json

{
  "amount": 0
}

###
GET localhost:8102/accounts
###
GET localhost:8101/accounts

###
POST http://localhost:8101/transfer
Content-Type: application/json

{
  "sourceSubAccount": 5,
  "targetAccountId": 1,
  "targetSubAccount": 2,
  "amount": 30
}

###
POST http://localhost:8102/transfer
Content-Type: application/json

{
  "targetAccountId": 1,
  "amount": 110
}

###
GET localhost:8102/amount

