###
POST http://localhost:8101/create
Content-Type: application/json

{
  "amount": 120
}

###
GET localhost:8101/amount

###
GET localhost:8102/amount

###
POST http://localhost:8101/transfer
Content-Type: application/json

{
  "targetAccountId": 2,
  "amount": 11
}

###
GET localhost:8102/amount

