###
GET localhost:8101/amount

###
POST localhost:8101/amount/100

###
POST localhost:8101/amount/17


###
GET localhost:8102/amount

###
POST localhost:8102/amount/98

###
POST localhost:8102/amount/11